apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-java-app
  labels:
    app: sample-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-java-app
  template:
    metadata:
      labels:
        app: sample-java-app
    spec:
      containers:
      - name: java-app-container
        image: docker.io/tushar3569/sample-java-app:latest
        ports:
        - containerPort: 9090
        env:
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 20
          periodSeconds: 5
