apiVersion: v1
kind: Service
metadata:
  name: sample-java-app-service
  labels:
    app: sample-java-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  selector:
    app: sample-java-app
